-- 0005: a book of its own.
--
-- The frontend's persisted blob carries `Book::independent` — the mark the
-- conflict sheet puts on a second row of one file when the reader answers *as
-- new* rather than *link them* — and a column the blob has and the catalog does
-- not is a value that survives a restart in one store and not the other. The
-- two hold the same library, so they carry the same shape of it.
--
-- The mark is not cosmetic. It is what the highlights are keyed by: a shared
-- row's marks live at its address, which every row at that address reads, and
-- a private row's live under a key carrying its id, which nothing else in the
-- library can name. A catalog that dropped the column would not lose a flag,
-- it would move a reader's highlights to a key the book no longer reads.
--
-- Zero is the whole of the migration's semantics, and nothing is rewritten:
-- every row written before this column existed was a shared row, because
-- nothing before it could mint anything else.
--
-- The fingerprint's UNIQUE constraint is left exactly as it is. This column
-- says whether a row keeps its own side data; whether the catalog may hold two
-- rows of one file at all is a different question, and one the frontend's
-- conflict sheet already answers for the blob without the catalog being wired
-- up to disagree with it.

ALTER TABLE books ADD COLUMN independent INTEGER NOT NULL DEFAULT 0;
