// Entry point: runs every engine-smoke scenario in document order.
// Compiled by the Trunk pre-build hook to scripts/test-engine-smoke.js;
// CI runs it with plain `node`.
//
// EXCEPTION: scripts/engine-smoke/*.js are tracked alongside the .ts
// sources because this file imports the compiled `.js` modules (plain
// Node, no tsx). Regenerated by `tsc -p tsconfig.scripts.json`.

(async () => {
  await (await import("./engine-smoke/open.js")).run();
  await (await import("./engine-smoke/render.js")).run();
  await (await import("./engine-smoke/theme.js")).run();
  await (await import("./engine-smoke/thumbnail.js")).run();
  await (await import("./engine-smoke/blend.js")).run();
  await (await import("./engine-smoke/teardown.js")).run();
  console.log("ALL ENGINE TESTS PASSED");
})().catch((e: unknown) => {
  console.error("TEST FAILURE:", e);
  process.exit(1);
});
