// Version-sync check — the cheapest insurance in the release pipeline. The
// app version lives in FOUR places: package.json (.version),
// src-tauri/tauri.conf.json (.version — what Tauri bundles), Cargo.toml
// (pdf-reader, [package].version) and src-tauri/Cargo.toml (pdf,
// [package].version). Release tags and artifact filenames derive from it, so
// any drift breaks releases invisibly; this script fails CI when they
// disagree. Tag-vs-version agreement is validated by the release workflow's
// metadata job, the only place a tag is in hand.
//
// Cargo.lock is checked against the same number, for the two workspace members
// that carry it. It is a generated file, but generated by cargo on the next
// resolve — and a CI run resolves in memory and throws the result away, so
// nothing ever wrote the bump back. `pdf` sat at 0.7.0 in the committed lock
// through a whole 0.8.0 release with all four sources above in agreement, and
// the only thing that noticed was a `--locked` build failing three lanes at
// once with "cannot update the lock file" and no reason attached. Reading it
// here names the file and the number instead, in the lane that finishes first.
//
// TypeScript source; Trunk's pre-build hook compiles it to
// `scripts/check-versions.js`.

import { isFile, read } from "./repo.js";

type VersionSource = [file: string, version: string];

function readJson(rel: string): unknown {
  return JSON.parse(read(rel));
}

function readCargoVersion(rel: string): string {
  const text = read(rel);
  const m = /^version\s*=\s*"([^"]+)"/m.exec(text);
  if (!m || !m[1]) throw new Error(`no [package] version found in ${rel}`);
  return m[1];
}

const LOCK = "Cargo.lock";

/** The version Cargo.lock records for a workspace member. Both names this is
 *  asked for are unique in the lock — registry crates can appear more than
 *  once at different versions, our own cannot — so the first block that names
 *  the package is the right one. */
function readLockVersion(pkg: string): string {
  for (const block of read(LOCK).split("[[package]]")) {
    if (/^name = "([^"]+)"/m.exec(block)?.[1] !== pkg) continue;
    const version = /^version = "([^"]+)"/m.exec(block)?.[1];
    if (!version) throw new Error(`no version for ${pkg} in ${LOCK}`);
    return version;
  }
  throw new Error(`${pkg} is missing from ${LOCK} — run cargo and commit it`);
}

const sources: VersionSource[] = [
  ["package.json", (readJson("package.json") as { version: string }).version],
  [
    "src-tauri/tauri.conf.json",
    (readJson("src-tauri/tauri.conf.json") as { version: string }).version,
  ],
  ["Cargo.toml", readCargoVersion("Cargo.toml")],
  ["src-tauri/Cargo.toml", readCargoVersion("src-tauri/Cargo.toml")],
  [`${LOCK} (pdf-reader)`, readLockVersion("pdf-reader")],
  [`${LOCK} (pdf)`, readLockVersion("pdf")],
];

const versions = new Set(sources.map(([, v]) => v));
if (versions.size !== 1) {
  console.error("::error::Version mismatch across files:");
  for (const [file, v] of sources) console.error(`  ${file}: ${v}`);
  process.exit(1);
}

const version = sources[0]![1];
console.log(`versions agree: ${version}`);

// ---------------------------------------------------------------------------
// Engine facade vs Rust bridge contract. crates/pdf-engine/src/bridge.rs is
// the sole place `window.PDFReader.*` is declared; a rename on either side
// fails at RUNTIME with no build error (the wasm shim just gets undefined),
// so this cross-checks the compiled facade (public/pdfEngine.js, from the
// build:ts step) against every extern the bridge declares under the
// PDFReader namespace.
// ---------------------------------------------------------------------------
const BRIDGE = "crates/pdf-engine/src/bridge.rs";
const FACADE = "public/pdfEngine.js";

function bridgePdfReaderNames(bridgeSrc: string): string[] {
  // Only `extern "C"` declarations are window.PDFReader surface
  // (`listen`/`has_pdf_reader` are plain pub fns). The attribute comes on
  // its own line before the fn: carry it until the fn it decorates, then
  // consume it — an unused attribute would misattribute the NEXT fn.
  const names: string[] = [];
  const lines = bridgeSrc.split(/\r?\n/);
  let inExtern = false;
  let attr: { pdfreader: boolean; jsName: string | null } | null = null;
  for (const line of lines) {
    if (line.includes('extern "C"')) {
      inExtern = true;
      continue;
    }
    if (inExtern && /^\s*}\s*$/.test(line)) {
      inExtern = false;
      attr = null;
      continue;
    }
    if (!inExtern) continue;
    const am = /#\[wasm_bindgen\(([^)]*)\)\]/.exec(line);
    if (am) {
      const a = am[1]!;
      attr = {
        pdfreader: a.includes('js_namespace = ["window", "PDFReader"]'),
        jsName: (/js_name\s*=\s*"(\w+)"/.exec(a) ?? [])[1] ?? null,
      };
      continue;
    }
    const fm = /pub\s+(?:async\s+)?fn\s+(\w+)/.exec(line);
    if (fm && attr) {
      if (attr.pdfreader) names.push(attr.jsName ?? fm[1]!);
      attr = null;
      continue;
    }
  }
  return names;
}

if (isFile(FACADE)) {
  const bridgeSrc = read(BRIDGE);
  const facadeSrc = read(FACADE);
  const missing: string[] = [];
  for (const name of bridgePdfReaderNames(bridgeSrc)) {
    // The facade is a shorthand object literal; the LAST property can carry
    // no trailing comma, so accept `,`, `:` or the closing `}`.
    const re = new RegExp(`\\b${name}\\s*[,:}]`);
    if (!re.test(facadeSrc)) missing.push(name);
  }
  if (missing.length > 0) {
    console.error(`::error::PDFReader facade is missing bridge bindings: ${missing.join(", ")}`);
    process.exit(1);
  }
  console.log(`engine facade matches the Rust bridge (${bridgePdfReaderNames(bridgeSrc).length} bindings)`);
} else {
  console.log("public/pdfEngine.js not built yet — facade check skipped");
}
